### ISSUE TITLE
Implement Code Formatting Tip

### ISSUE THREAD

**Issue by stephencorwin** [pmndrs/discord#2]
## Overview
Whenever someone posts code in the channel, it is much more readable whenever it is formatted with syntax highlighting.

## Proposed Solution
Listen to messages that include a ``` and determine it includes "js", "ts", or "jsx" (tsx is not supported by discord). If a determination is made, respond with a message something to the effect of:
> **TIP:** Discord supports syntax highlighting by decorating the first ``` of a code block with a language id (ts, js, jsx, css, html, bash).
> \`\`\`ts
> // input
> console.log('Hello World')
> \`\`\`
> ```ts
> // output
> console.log('Hello World')
> ```

**Comment by CodyJasonBennett** [comment]
How would the language determination influence the message?
Could a stock message work like the one you listed above?

**Comment by stephencorwin** [comment]
I would probably just use a stock message regardless of whatever language is discovered.
