### ISSUE TITLE
Code formatting TIP responds when already formatted

### ISSUE THREAD

**Issue by stephencorwin** [pmndrs/discord#4]
Whenever a formatted code block has any text after the closing \`\`\`, the bot will respond with a message. This is due to how we are detecting unformatted code due to a new line character \n.

In addition to fixing this false positive, I would like to change the frequency of how often the tip is sent. We should reply every 3rd unformatted message instead of after every one. This will help with the spam while still encouraging folks to use formatted code blocks. We can probably accomplish this by just incrementing a counter in global scope.

cc @CodyJasonBennett

**Comment by CodyJasonBennett** [comment]
This was an oversight on my part.
I had the watcher pair and validate the starting and closing markdown in addition to spacing messages.
